secret_path         = "/home/flavien/projectClientDeploment/secret.ini"
region              = "us-east-1"
private_key_path    = "/home/flavien/projectClientDeploment/flavien.pem"
ec2_avail_zone      = "us-east-1a"
author_name         = "flavien"
main_dir            = "/home/flavien/projectClientDeploment"
